-- 코드를 입력하세요
SELECT
    MEMBER_PROFILE.MEMBER_ID, 
    MEMBER_PROFILE.MEMBER_NAME,
    MEMBER_PROFILE.GENDER, 
    DATE_FORMAT(MEMBER_PROFILE.DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
    FROM MEMBER_PROFILE
    WHERE MEMBER_PROFILE.TLNO IS NOT NULL
        AND DATE_FORMAT(MEMBER_PROFILE.DATE_OF_BIRTH, '%m') = '03'
        AND GENDER = 'W'
    ORDER BY MEMBER_PROFILE.MEMBER_ID